version: '3'
services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    networks:
      - dockermonitoring_network_DinD  # Utilisez le m..me nom de r..seau que dans l'autre machine

    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'

networks:
  dockermonitoring_network_DinD:
    external:  # Utilisez le m..me r..seau externe que dans l'autre machine
      name: dockermonitoring_network_DinD

